### ISSUE TITLE
__on_error() missing 1 required positional argument: 'message'

### ISSUE THREAD

**Issue by sundevilyang** [noda-sin/ebisu#12]
Hey, 
after run `python main.py --demo --strategy Doten` command, it showed the following error
```
2020-01-23 12:23:59,361 - INFO - Bot Mode : Trade
2020-01-23 12:23:59,363 - INFO - Starting Bot
2020-01-23 12:23:59,363 - INFO - Strategy : Doten
2020-01-23 12:25:14,856 - ERROR - error from callback <bound method BitMexWs.__on_error of <src.bitmex_websocket.BitMexWs object at 0x1370ccb00>>: __on_error() missing 1 required positional argument: 'message'
2020-01-23 12:25:14,856 - ERROR - error from callback <bound method BitMexWs.__on_close of <src.bitmex_websocket.BitMexWs object at 0x1370ccb00>>: __on_close() missing 1 required positional argument: 'ws'
Traceback (most recent call last):
  File "/Users/ywen8/.pyenv/versions/3.6.5/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/ywen8/.pyenv/versions/3.6.5/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/Users/ywen8/.pyenv/versions/3.6.5/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out
```

**Comment by haikalfouzi** [comment]
try downgrading websocket 
[https://github.com/BitMEX/sample-market-maker/issues/166#issuecomment-427238417](https://github.com/BitMEX/sample-market-maker/issues/166#issuecomment-427238417)

**Comment by erocitna** [comment]
I think using older version of websocket-client like 0.52.0 works. Try uninstalling the one you are using and installing 0.52.0.
