### ISSUE TITLE
invalid syntax / modulenotfounderror

### ISSUE THREAD

**Issue by saramg963** [noda-sin/ebisu#13]
python3 main.py --strategy strategy
Traceback (most recent call last):
  File "/home/ooo/ta-lib/ebisu/src/factory.py", line 16, in create
    cls = getattr(strategy, args.strategy)
AttributeError: module 'src.strategy' has no attribute 'strategy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 20, in <module)
    bot = BotFactory.create(args)
  File "/home/ooo/ta-lib/ebisu/src/factory.py", line 24, in create
    raise Exception(f"Not Found Strategy : {args.strategy}")
Exception: Not Found Strategy : strategy

how can i solve this? help plz

**Comment by saramg963** [comment]
> ooo:~$ cd ebisu ooo:~/ebisu$ python main.py
> Traceback (most recent call last):
> File "main.py", line 8, in <module
> from src.factory import BotFactory
> File "/home/ooo/ebisu/src/**init**.py", line 210
> def notify(message: object, fileName: object = None) -> object:
> ^
> SyntaxError: invalid syntax
> 
> :~/ebisu$ python3 main.py --strategy STRATEGY
> Traceback (most recent call last):
> File "main.py", line 8, in <module
> from src.factory import BotFactory
> File "/home/ooo/ebisu/src/**init**.py", line 10, in <module
> import numpy as np
> ModuleNotFoundError: No module named 'numpy'
> 
> I already installed numpy by using pip3 install numpy, sudo apt install python3-pip
> how can I solve this problem? help
