### ISSUE TITLE
has no attribute 'strategy'

### ISSUE THREAD

**Issue by saramg963** [noda-sin/ebisu#14]
~/ebisu$ python3 main.py --strategy strategy
Traceback (most recent call last):
  File "/home/ooo/ebisu/src/factory.py", line 16, in create
    cls = getattr(strategy, args.strategy)
AttributeError: module 'src.strategy' has no attribute 'strategy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 20, in <module>
    bot = BotFactory.create(args)
  File "/home/ooo/ebisu/src/factory.py", line 24, in create
    raise Exception(f"Not Found Strategy : {args.strategy}")
Exception: Not Found Strategy : strategy

I can't solve this.. help plz

**Comment by haikalfouzi** [comment]
you used the wrong input argument for strategy. look at strategy.py for the list of prebuilt strategy, and your command should look like this
`python main.py --strategy OCC`
you can replace OCC with the prebuilt strategy such as Doten, SMA, Rci
