### ISSUE TITLE
Truble with main.py and bot.py

### ISSUE THREAD

**Issue by sty0133** [noda-sin/ebisu#18]
here is my error when I did " python main.py --demo --strategy Doten "

`$ python main.py --demo --strategy Doten
2021-03-16 18:38:19,828 - INFO - Bot Mode : Trade
2021-03-16 18:38:19,828 - INFO - Starting Bot
2021-03-16 18:38:19,829 - INFO - Strategy : Doten
2021-03-16 18:38:21,377 - ERROR - error from callback <bound method BitMexWs.__on_error of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_error() missing 1 required positional argument: 'message'
2021-03-16 18:38:21,377 - ERROR - error from callback <bound method BitMexWs.__on_close of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_close() missing 1 required positional argument: 'ws'
C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\swagger_spec_validator\validator20.py:53: SwaggerValidationWarning: Found "$ref: #/definitions/UserPreferences" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/User/properties/preferences)
  ref_dict['$ref'], '/'.join(path),
2021-03-16 18:38:22,340 - ERROR - error from callback <bound method BitMexWs.__on_error of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_error() missing 1 required positional argument: 'message'
2021-03-16 18:38:22,340 - ERROR - error from callback <bound method BitMexWs.__on_close of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_close() missing 1 required positional argument: 'ws'
2021-03-16 18:38:23,315 - ERROR - error from callback <bound method BitMexWs.__on_error of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_error() missing 1 required positional argument: 'message'
2021-03-16 18:38:23,316 - ERROR - error from callback <bound method BitMexWs.__on_close of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_close() missing 1 required positional argument: 'ws'
2021-03-16 18:38:24,334 - ERROR - error from callback <bound method BitMexWs.__on_error of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_error() missing 1 required positional argument: 'message'
2021-03-16 18:38:24,334 - ERROR - error from callback <bound method BitMexWs.__on_close of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_close() missing 1 required positional argument: 'ws'
Traceback (most recent call last):
  File "C:\Users\hwang\Desktop\ebisu\src\__init__.py", line 94, in retry
    ret, res = func()
  File "C:\Users\hwang\Desktop\ebisu\src\bitmex.py", line 119, in <lambda>
    .User.User_getMargin(currency="XBt").result())
  File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 271, in result
    swagger_result = self._get_swagger_result(incoming_response)
  File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 124, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 303, in _get_swagger_result
    self.request_config.response_callbacks,
  File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 353, in unmarshal_response
    raise_on_expected(incoming_response)
  File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 422, in raise_on_expected
    swagger_result=http_response.swagger_result)
bravado.exception.HTTPUnauthorized: 401 Unauthorized: {'error': {'message': 'Invalid API Key.', 'name': 'HTTPError'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 22, in <module>
    bot.run()
  File "C:\Users\hwang\Desktop\ebisu\src\bot.py", line 127, in run
    logger.info(f"Balance : {self.exchange.get_balance()}")
  File "C:\Users\hwang\Desktop\ebisu\src\bitmex.py", line 107, in get_balance
    return self.get_margin()["walletBalance"]
  File "C:\Users\hwang\Desktop\ebisu\src\bitmex.py", line 118, in get_margin
    self.margin = retry(lambda: self.private_client
  File "C:\Users\hwang\Desktop\ebisu\src\__init__.py", line 112, in retry
    raise FatalError(error)
src.FatalError: 401 Unauthorized: {'error': {'message': 'Invalid API Key.', 'name': 'HTTPError'}}
`

AND here is my error when I did " python main.py --strategy TV "

`$ python main.py --strategy TV
2021-03-16 18:41:59,158 - INFO - Bot Mode : Trade
2021-03-16 18:41:59,158 - INFO - Starting Bot
2021-03-16 18:41:59,158 - INFO - Strategy : TV
C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\swagger_spec_validator\validator20.py:53: SwaggerValidationWarning: Found "$ref: #/definitions/UserPreferences" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/User/properties/preferences)
  ref_dict['$ref'], '/'.join(path),
Traceback (most recent call last):
  File "C:\Users\hwang\Desktop\ebisu\src\__init__.py", line 94, in retry
    ret, res = func()
  File "C:\Users\hwang\Desktop\ebisu\src\bitmex.py", line 119, in <lambda>
    .User.User_getMargin(currency="XBt").result())
  File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 271, in result
    swagger_result = self._get_swagger_result(incoming_response)
  File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 124, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 303, in _get_swagger_result
    self.request_config.response_callbacks,
  File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 353, in unmarshal_response
    raise_on_expected(incoming_response)
  File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 422, in raise_on_expected
    swagger_result=http_response.swagger_result)
bravado.exception.HTTPUnauthorized: 401 Unauthorized: {'error': {'message': 'Invalid API Key.', 'name': 'HTTPError'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 22, in <module>
    bot.run()
  File "C:\Users\hwang\Desktop\ebisu\src\strategy.py", line 221, in run
    logger.info(f"Balance : {self.exchange.get_balance()}")
  File "C:\Users\hwang\Desktop\ebisu\src\bitmex.py", line 107, in get_balance
    return self.get_margin()["walletBalance"]
  File "C:\Users\hwang\Desktop\ebisu\src\bitmex.py", line 118, in get_margin
    self.margin = retry(lambda: self.private_client
  File "C:\Users\hwang\Desktop\ebisu\src\__init__.py", line 112, in retry
    raise FatalError(error)
src.FatalError: 401 Unauthorized: {'error': {'message': 'Invalid API Key.', 'name': 'HTTPError'}}
`

everything like this error
I did "source ~/.bash_profile"
and my bash_profile is like this

`export BITMEX_TEST_APIKEY=oJ8w4XXXXXXXXXXXXXXXXXXXXXXfhnQ
export BITMEX_TEST_SECRET=SvlbbnXXXXXXXXXXXXXXXXXXXXXXXXL2eRI
export LINE_APIKEY=Uf252XXXXXXXXXXX22c92d
export GMAIL_ADDRESS=hXXXXXXXXXX9@gmail.com
`

I really wanna use this bot so can someone help me?

**Comment by sty0133** [comment]
> here is my error when I did " python main.py --demo --strategy Doten "
> 
> `$ python main.py --demo --strategy Doten
> 2021-03-16 18:38:19,828 - INFO - Bot Mode : Trade
> 2021-03-16 18:38:19,828 - INFO - Starting Bot
> 2021-03-16 18:38:19,829 - INFO - Strategy : Doten
> 2021-03-16 18:38:21,377 - ERROR - error from callback <bound method BitMexWs.__on_error of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_error() missing 1 required positional argument: 'message'
> 2021-03-16 18:38:21,377 - ERROR - error from callback <bound method BitMexWs.__on_close of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_close() missing 1 required positional argument: 'ws'
> C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\swagger_spec_validator\validator20.py:53: SwaggerValidationWarning: Found "$ref: #/definitions/UserPreferences" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/User/properties/preferences)
> ref_dict['$ref'], '/'.join(path),
> 2021-03-16 18:38:22,340 - ERROR - error from callback <bound method BitMexWs.__on_error of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_error() missing 1 required positional argument: 'message'
> 2021-03-16 18:38:22,340 - ERROR - error from callback <bound method BitMexWs.__on_close of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_close() missing 1 required positional argument: 'ws'
> 2021-03-16 18:38:23,315 - ERROR - error from callback <bound method BitMexWs.__on_error of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_error() missing 1 required positional argument: 'message'
> 2021-03-16 18:38:23,316 - ERROR - error from callback <bound method BitMexWs.__on_close of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_close() missing 1 required positional argument: 'ws'
> 2021-03-16 18:38:24,334 - ERROR - error from callback <bound method BitMexWs.__on_error of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_error() missing 1 required positional argument: 'message'
> 2021-03-16 18:38:24,334 - ERROR - error from callback <bound method BitMexWs.__on_close of <src.bitmex_websocket.BitMexWs object at 0x0000021C2839A908>>: __on_close() missing 1 required positional argument: 'ws' Traceback (most recent call last): File "C:\Users\hwang\Desktop\ebisu\src__init__.py", line 94, in retry
> ret, res = func()
> File "C:\Users\hwang\Desktop\ebisu\src\bitmex.py", line 119, in
> .User.User_getMargin(currency="XBt").result())
> File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 271, in result
> swagger_result = self._get_swagger_result(incoming_response)
> File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 124, in wrapper
> return func(self, *args, **kwargs)
> File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 303, in _get_swagger_result
> self.request_config.response_callbacks,
> File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 353, in unmarshal_response
> raise_on_expected(incoming_response)
> File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 422, in raise_on_expected
> swagger_result=http_response.swagger_result)
> bravado.exception.HTTPUnauthorized: 401 Unauthorized: {'error': {'message': 'Invalid API Key.', 'name': 'HTTPError'}}
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "main.py", line 22, in
> bot.run()
> File "C:\Users\hwang\Desktop\ebisu\src\bot.py", line 127, in run
> logger.info(f"Balance : {self.exchange.get_balance()}")
> File "C:\Users\hwang\Desktop\ebisu\src\bitmex.py", line 107, in get_balance
> return self.get_margin()["walletBalance"]
> File "C:\Users\hwang\Desktop\ebisu\src\bitmex.py", line 118, in get_margin
> self.margin = retry(lambda: self.private_client
> File "C:\Users\hwang\Desktop\ebisu\src__init__.py", line 112, in retry
> raise FatalError(error)
> src.FatalError: 401 Unauthorized: {'error': {'message': 'Invalid API Key.', 'name': 'HTTPError'}}
> `
> 
> AND here is my error when I did " python main.py --strategy TV "
> 
> `$ python main.py --strategy TV
> 2021-03-16 18:41:59,158 - INFO - Bot Mode : Trade
> 2021-03-16 18:41:59,158 - INFO - Starting Bot
> 2021-03-16 18:41:59,158 - INFO - Strategy : TV
> C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\swagger_spec_validator\validator20.py:53: SwaggerValidationWarning: Found "$ref: #/definitions/UserPreferences" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/User/properties/preferences)
> ref_dict['$ref'], '/'.join(path),
> Traceback (most recent call last):
> File "C:\Users\hwang\Desktop\ebisu\src__init__.py", line 94, in retry
> ret, res = func()
> File "C:\Users\hwang\Desktop\ebisu\src\bitmex.py", line 119, in
> .User.User_getMargin(currency="XBt").result())
> File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 271, in result
> swagger_result = self._get_swagger_result(incoming_response)
> File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 124, in wrapper
> return func(self, *args, **kwargs)
> File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 303, in _get_swagger_result
> self.request_config.response_callbacks,
> File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 353, in unmarshal_response
> raise_on_expected(incoming_response)
> File "C:\Users\hwang\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 422, in raise_on_expected
> swagger_result=http_response.swagger_result)
> bravado.exception.HTTPUnauthorized: 401 Unauthorized: {'error': {'message': 'Invalid API Key.', 'name': 'HTTPError'}}
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "main.py", line 22, in
> bot.run()
> File "C:\Users\hwang\Desktop\ebisu\src\strategy.py", line 221, in run
> logger.info(f"Balance : {self.exchange.get_balance()}")
> File "C:\Users\hwang\Desktop\ebisu\src\bitmex.py", line 107, in get_balance
> return self.get_margin()["walletBalance"]
> File "C:\Users\hwang\Desktop\ebisu\src\bitmex.py", line 118, in get_margin
> self.margin = retry(lambda: self.private_client
> File "C:\Users\hwang\Desktop\ebisu\src__init__.py", line 112, in retry
> raise FatalError(error)
> src.FatalError: 401 Unauthorized: {'error': {'message': 'Invalid API Key.', 'name': 'HTTPError'}}
> `
> 
> everything like this error
> I did "source ~/.bash_profile"
> and my bash_profile is like this
> 
> `export BITMEX_TEST_APIKEY=oJ8w4XXXXXXXXXXXXXXXXXXXXXXfhnQ export BITMEX_TEST_SECRET=SvlbbnXXXXXXXXXXXXXXXXXXXXXXXXL2eRI export LINE_APIKEY=Uf252XXXXXXXXXXX22c92d export GMAIL_ADDRESS=hXXXXXXXXXX9@gmail.com `
> 
> I really wanna use this bot so can someone help me?
