### ISSUE TITLE
Strategy OCCについて

### ISSUE THREAD

**Issue by surume-ika** [noda-sin/ebisu#4]
@noda-sin 様　いつもありがとうございます！また開発本当にお疲れ様です！ストラテジーも追加されていてとても嬉しかったです！

昨日からOCCで稼働していて先ほどLINEにエラーが出ていたので共有させていただきます！
GCPで運用してました。(エラーが出たあとは、止まらず常に吐き続けていました。)
下記にログを添付します！

Lineに送られてきたエラーです。
`
Ebisu-mex: Traceback (most recent call last):
  File "/home/GCP/.pyenv/versions/3.6.5/lib/python3.6/site-packages/talib/__init__.py", line 20, in wrapper
    for arg in chain(args, kwargs.values())
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/GCP/ebisu/src/bitmex.py", line 485, in __update_ohlcv
    self.strategy(open, close, high, low, volume)
  File "/home/GCP/ebisu/src/strategy.py", line 111, in strategy
    dema_close = dema(close, basis_len)
  File "/home/GCP/ebisu/src/strategy.py", line 109, in dema
    return 2 * a - ema(a, length)
  File "/home/GCP/ebisu/src/__init__.py", line 145, in ema
    return talib.EMA(np.array(source), period)
  File "/home/GCP/.pyenv/versions/3.6.5/lib/python3.6/site-packages/talib/__init__.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "talib/_func.pxi", line 7091, in talib._ta_lib.EMA
`

nohup.outのlogになります。

`

2018-07-23 13:30:15,178 - ERROR - An error occurred. inputs are all NaN
2018-07-23 13:30:15,178 - ERROR - An error occurred. inputs are all NaN
2018-07-23 13:30:15,178 - ERROR - An error occurred. inputs are all NaN
2018-07-23 13:30:15,179 - ERROR - Traceback (most recent call last):
  File "/home/GCP/.pyenv/versions/3.6.5/lib/python3.6/site-packages/talib/__init__.py", line 20, in wrapper
    for arg in chain(args, kwargs.values())
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/GCP/ebisu/src/bitmex.py", line 485, in __update_ohlcv
    self.strategy(open, close, high, low, volume)
  File "/home/GCP/ebisu/src/strategy.py", line 111, in strategy
    dema_close = dema(close, basis_len)
  File "/home/GCP/ebisu/src/strategy.py", line 109, in dema
    return 2 * a - ema(a, length)
  File "/home/GCP/ebisu/src/__init__.py", line 145, in ema
    return talib.EMA(np.array(source), period)
  File "/home/GCP/.pyenv/versions/3.6.5/lib/python3.6/site-packages/talib/__init__.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "talib/_func.pxi", line 7091, in talib._ta_lib.EMA
Exception: inputs are all NaN
2018-07-23 13:31:15,139 - ERROR - An error occurred. inputs are all NaN
2018-07-23 13:31:15,139 - ERROR - Traceback (most recent call last):
  File "/home/GCP/.pyenv/versions/3.6.5/lib/python3.6/site-packages/talib/__init__.py", line 20, in wrapper
    for arg in chain(args, kwargs.values())
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/GCP/ebisu/src/bitmex.py", line 485, in __update_ohlcv
    self.strategy(open, close, high, low, volume)
  File "/home/GCP/ebisu/src/strategy.py", line 111, in strategy
    dema_close = dema(close, basis_len)
  File "/home/GCP/ebisu/src/strategy.py", line 109, in dema
    return 2 * a - ema(a, length)
  File "/home/GCP/ebisu/src/__init__.py", line 145, in ema
    return talib.EMA(np.array(source), period)
  File "/home/GCP/.pyenv/versions/3.6.5/lib/python3.6/site-packages/talib/__init__.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "talib/_func.pxi", line 7091, in talib._ta_lib.EMA
Exception: inputs are all NaN

`

何か参考になれば幸いです！

**Comment by noda-sin** [comment]
ありがとうございます。
まだ不安定版ですが、いきなり実践投入されるなんてなかなかチャレンジャーですね．．．

**Comment by surume-ika** [comment]
@noda-sin 様　不安定なんですか！！知らなかったです！！？w
でもちゃんと稼働しております！！DotenもRciもしっかりと利益だしてくれております！！
ある程度利益が積もったら投げ銭もしっかりさせていただきます！今後も開発すごく楽しみにしております！

**Comment by noda-sin** [comment]
バージョン切ってるので、そちらを使ってくれれば嬉しいっす！
対象のバグは、今直してるので、今夜ぐらいにFIX版だせるかと思います。
>でもちゃんと稼働しております！！DotenもRciもしっかりと利益だしてくれております！！
えぇ！？自分でも驚いているのですが．．．よかったです。

**Comment by noda-sin** [comment]
@surume-ika さん
一応、エラーは取りきれていますが、OCCはまだ検証中のロジックのため、
利益がでなくてもご了承ください。

**Comment by surume-ika** [comment]
ありがとうございます！どんどんトライしていきます！！w
