### ISSUE TITLE
"ERROR - Handshake status 400 Bad Request" and then "ERROR - Handshake status 429 Too Many Requests"

### ISSUE THREAD

**Issue by xiaoxin233** [noda-sin/ebisu#5]
2018-08-02 23:13:34,556 - ERROR - Handshake status 400 Bad Request
2018-08-02 23:13:34,558 - ERROR - Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_app.py", line 236, in run_forever
    host=host, origin=origin)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_handshake.py", line 135, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message)
websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request

2018-08-02 23:13:35,536 - ERROR - Handshake status 400 Bad Request
2018-08-02 23:13:35,536 - ERROR - Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_app.py", line 236, in run_forever
    host=host, origin=origin)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_handshake.py", line 135, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message)
websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request
.
.
.
(same error about 200 times in 90 seconds)
.
.
.

2018-08-02 23:15:06,825 - ERROR - Handshake status 400 Bad Request
2018-08-02 23:15:06,826 - ERROR - Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_app.py", line 236, in run_forever
    host=host, origin=origin)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_handshake.py", line 135, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message)
websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request

2018-08-02 23:15:06,848 - ERROR - Handshake status 429 Too Many Requests
2018-08-02 23:15:06,849 - ERROR - Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_app.py", line 236, in run_forever
    host=host, origin=origin)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_handshake.py", line 135, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message)
websocket._exceptions.WebSocketBadStatusException: Handshake status 429 Too Many Requests

2018-08-02 23:15:06,875 - ERROR - Handshake status 429 Too Many Requests
2018-08-02 23:15:06,875 - ERROR - Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_app.py", line 236, in run_forever
    host=host, origin=origin)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/python3.6/lib/python3.6/site-packages/websocket/_handshake.py", line 135, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message)
websocket._exceptions.WebSocketBadStatusException: Handshake status 429 Too Many Requests
.
.
.
(The error 429 never stopped until I kill the process)

**Comment by surume-ika** [comment]
Hi @xiaoxin233 .

I got this same issue before. 

Handshake means Bitmex could not authorise your API key.

Please check your api key correctly. (~./bash_Profile)

After add MEXAPI Key , reflesh the bash_Profile.  ( source ~./bash_profile )

please check it.
